[target.'cfg(all())']
rustflags = [
    "-Wclippy::all",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::cast_lossless",
    "-Wclippy::checked_conversions",
    "-Wclippy::dbg_macro",
    "-Wclippy::disallowed_methods",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_ok_or",
    "-Wclippy::map_flatten",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_wild_err_arm",
    "-Wclippy::needless_borrow",
    "-Wclippy::option_option",
    "-Wclippy::same_functions_in_if_condition",
    "-Wclippy::single_match_else",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::unnecessary_mut_passed",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
    "-Wtrivial_numeric_casts",
    "-Wunused_lifetimes",
    "-Wunused_qualifications"
]
